import requests
import os

# LIVE TOKEN FOR THE DEMO VIDEO (Set locally; do not commit secrets)
GITLAB_TOKEN = os.getenv("GITLAB_TOKEN", "YOUR_GITLAB_ACCESS_TOKEN_HERE")

# Your exact GitLab Project ID
GITLAB_PROJECT_ID = os.getenv("GITLAB_PROJECT_ID", "82313809")


def execute_gitlab_incident(title: str, description: str):
    """Actually hits the real GitLab API to create an incident issue!"""
    if GITLAB_TOKEN == "YOUR_GITLAB_ACCESS_TOKEN_HERE" or GITLAB_TOKEN == "":
        return "Simulation Mode: Real GitLab API token not provided."

    url = f"https://gitlab.com/api/v4/projects/{GITLAB_PROJECT_ID}/issues"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    payload = {
        "title": f"[AEGIS SWARM] {title}",
        "description": f"### Autonomous Threat Intelligence Report\n\n**Generated by Purple Commander (Gemini 2.5 Pro)**\n\n```yaml\n{description}\n```",
        "labels": "security,aegis,auto-generated"
    }

    try:
        response = requests.post(url, headers=headers, data=payload)
        if response.status_code == 201:
            issue_url = response.json().get("web_url")
            return f"Success! Real GitLab Issue created: {issue_url}"
        else:
            return f"GitLab API Error: {response.status_code} - {response.text}"
    except Exception as e:
        return str(e)
